import type { CodeTheme } from "@sarchauhan/code-markdown";

export const chatCodeThemes: Record<"light" | "dark", CodeTheme> = {
  light: {
    name: "chat-light",
    shikiTheme: "github-light",
    colors: {
      background: "#ffffff",
      foreground: "#0d0d0d",
      comment: "#6e6e80",
      keyword: "#9b174c",
      string: "#166534",
      function: "#1d4ed8",
      variable: "#0d0d0d",
      number: "#7c3aed",
      operator: "#9b174c",
      punctuation: "#6e6e80",
      type: "#0369a1",
      tag: "#166534",
      attribute: "#1d4ed8",
      constant: "#b45309",
      surface: "#f7f7f8",
      overlay: "#d8d8df",
      subtext: "#6e6e80",
    },
  },
  dark: {
    name: "chat-dark",
    shikiTheme: "github-dark",
    colors: {
      background: "#212121",
      foreground: "#ececec",
      comment: "#8f8f8f",
      keyword: "#ff7b72",
      string: "#a5d6a7",
      function: "#79c0ff",
      variable: "#ececec",
      number: "#d2a8ff",
      operator: "#ff7b72",
      punctuation: "#b4b4b4",
      type: "#79c0ff",
      tag: "#7ee787",
      attribute: "#79c0ff",
      constant: "#ffa657",
      surface: "#2f2f2f",
      overlay: "#454545",
      subtext: "#b4b4b4",
    },
  },
};
